name: pull

on:
  pull_request:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  unittest-linux:
    name: unittest-linux
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build and install
        run: scripts/ci.sh
